package Terceros;


/**
* Terceros/TerceroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Terceros.idl
* miércoles 26 de septiembre de 2018 21H16' COT
*/

public interface TerceroOperations 
{
  boolean insertarTercero (String nombre, String apellido, String telefono);
  boolean actualizarTercero (String nombre, String apellido, String telefono, int id);
  boolean eliminarTercero (int id);
  String consultarTercero (int id);
  void shoutdown ();
} // interface TerceroOperations
